version: "3"
services:
  console-service:
    build: .
    image: console
    tty: true
    stdin_open: true
    ports:
      - 8080:8080
    environment:
      TEZOS_CONSOLE_HTTP_HOST: 0.0.0.0
      TEZOS_CONSOLE_HTTP_PORT: 8080
